# Generated by Django 3.2.23 on 2023-12-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField()),
                ('location_address', models.CharField(max_length=255)),
                ('venue_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
